"""empty message

Revision ID: 0d10815976a2
Revises: 
Create Date: 2021-02-25 18:47:18.023160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d10815976a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grouppost', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_grouppost_group_id_group'), 'group', ['group_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('grouppost', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_grouppost_group_id_group'), type_='foreignkey')

    # ### end Alembic commands ###
