"""empty message

Revision ID: 1c55a4fc500b
Revises: a96cd8121951
Create Date: 2022-03-07 20:35:08.044866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c55a4fc500b'
down_revision = 'a96cd8121951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_group_title'), ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_group_title'), type_='unique')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###
