"""empty message

Revision ID: 88f2c96c9e7c
Revises: 
Create Date: 2021-02-22 00:36:02.026257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f2c96c9e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('group', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'language')
    op.drop_column('group', 'image_file')
    # ### end Alembic commands ###
