"""empty message

Revision ID: 98a8ca5fa8fb
Revises: 
Create Date: 2021-02-24 20:24:46.926210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a8ca5fa8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouppost', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'grouppost', type_='foreignkey')
    op.create_foreign_key(None, 'grouppost', 'group', ['group_id'], ['id'])
    op.drop_column('grouppost', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouppost', sa.Column('group', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'grouppost', type_='foreignkey')
    op.create_foreign_key(None, 'grouppost', 'group', ['group'], ['id'])
    op.drop_column('grouppost', 'group_id')
    # ### end Alembic commands ###
